apiVersion: 1

datasources:
  - name: StormRelay Prometheus
    uid: stormrelay-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.4.1
      cacheLevel: High
      incrementalQuerying: true
      disableRecordingRules: false
